services:
  prophet:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prophet_server
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
      - ./app:/app
    restart: unless-stopped